import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import Link from 'next/link'

// const defaultEndpoint = 'https://rickandmortyapi.com/api/character';
const defaultEndpoint = 'http://ted-talk-api.herokuapp.com/talks';


// export async function getServerSideProps({ query }) {
//   const { id } = query;
//   const res = await fetch(`${defaultEndpoint}/${id}`);
//   const data = await res.json();
//   return{
//     props: {
//       data
//     }
//   }
// }
export async function getServerSideProps({query}) {
  const {id} = query;
  const data = await axios(`${defaultEndpoint}/${id}`)
  .then(response =>{
    return response.data;
  })
  // const res = await axios.get(defaultEndpoint);
  // const data = await res.json();
  // console.log(data);
  return{
    props: {
      data
    }
  }
}


export default function Home({ data }) {
  const { title, img} = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {title} 
        </h1>
        <div className='profile'>
          <div className='profile-image'>
            <img src={ img } alt={title}/>
          </div>
          <div className='profile-detailes'>
            <h2>Character Detailes</h2>
            <ul>
              <li>
                <strong>Name:</strong> {title}
              </li>
            </ul>
          </div>
        </div>
        <p>
          <Link href='/'>
            <a>
              Back
            </a>
          </Link>
        </p>
      </main>
    </div>
  )
}